services:
  gateway:
    build:
      context: .                                   # root (serve per il go.mod)
      dockerfile: internal/services/gateway/cmd/Dockerfile
    image: sdcc/gateway:local
    ports: ["5008:5009"]

  dashboard:
    build:
      context: internal/services/dashboard/cmd     # <-- QUI cambia il contesto
      dockerfile: Dockerfile                       # il Dockerfile è in quella cartella
    image: sdcc/dashboard:local
    environment:
      GATEWAY_URL: http://gateway:5009
    ports: ["8081:8080"]
    depends_on: [gateway]
