apiVersion: apps/v1
kind: Deployment
metadata:
  name: deviceservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceservice
  template:
    metadata:
      labels:
        app: deviceservice
    spec:
      containers:
        - name: deviceservice
          image: deviceservice:latest
          imagePullPolicy: Never
          env:
            - name: RABBITMQ_HOST
              value: "192.168.49.2"
            - name: RABBITMQ_PORT
              value: "31883"
            - name: RABBITMQ_USER
              value: "mqtt_user"          # 👈 aggiunto
            - name: RABBITMQ_PASSWORD
              value: "mqtt_pwd"      # 👈 aggiunto
