apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-mqtt
  namespace: rabbitmq
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: rabbitmq
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      nodePort: 31883