apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: rabbitmq
data:
  enabled_plugins: |
    [rabbitmq_management, rabbitmq_mqtt].
  rabbitmq.conf: |
    ## Disabilita loopback per 'guest'
    loopback_users.guest = false

    ## AMQP & Management
    listeners.tcp.default = 5672
    management.tcp.port = 15672

    ## MQTT
    mqtt.listeners.tcp.default = 1883
    mqtt.allow_anonymous = false
    mqtt.vhost = /
    mqtt.exchange = amq.topic

---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-default-userpass
  namespace: rabbitmq
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "mqtt_user"
  RABBITMQ_DEFAULT_PASS: "mqtt_pwd"
