apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: rabbitmq
data:
  enabled_plugins: |
    [rabbitmq_management, rabbitmq_mqtt, rabbitmq_peer_discovery_k8s].
  rabbitmq.conf: |
    ## Disabilita loopback per 'guest'
    loopback_users.guest = false

    ## Listener
    listeners.tcp.default = 5672
    management.tcp.port = 15672

    ## MQTT
    mqtt.listeners.tcp.default = 1883
    mqtt.allow_anonymous = false
    mqtt.vhost = /
    mqtt.exchange = amq.topic

    ## Cluster formation via K8s (NO label_selector!)
    cluster_formation.peer_discovery_backend = k8s
    cluster_formation.k8s.address_type = hostname
    cluster_formation.k8s.service_name = rabbitmq-headless
    # Suggerimento (non obbligatorio): aiuta il discovery in bootstrap
    cluster_formation.target_cluster_size_hint = 3

    ## HA moderna
    default_queue_type = quorum
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: rabbitmq
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "mqtt_user"
  RABBITMQ_DEFAULT_PASS: "mqtt_pwd"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-erlang-cookie
  namespace: rabbitmq
type: Opaque
stringData:
  RABBITMQ_ERLANG_COOKIE: "SDCC_SUPER_SECRET_COOKIE_123456"
