apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-nodeport
  namespace: rabbitmq
  labels: { app: rabbitmq }
spec:
  type: NodePort
  selector: { app: rabbitmq }
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
      nodePort: 31883
    - name: amqp
      port: 5672
      targetPort: 5672
      nodePort: 30672
    - name: mgmt
      port: 15672
      targetPort: 15672
      nodePort: 31672
