apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-lb
  namespace: rabbitmq
  labels: { app: rabbitmq }
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    # (opzionale) limita l’accesso ai tuoi SG:
    # service.beta.kubernetes.io/aws-load-balancer-security-groups: "sg-xxxxxxxx,sg-yyyyyyyy"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector: { app: rabbitmq }
  ports:
    - { name: mqtt, port: 1883, targetPort: 1883 }
    - { name: amqp, port: 5672, targetPort: 5672 }
    - { name: mgmt, port: 15672, targetPort: 15672 }
