apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
  namespace: fog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-service
  template:
    metadata:
      labels:
        app: event-service
    spec:
      initContainers:
        - name: netem
          image: alpine:3.20
          securityContext:
            capabilities:
              add: [ "NET_ADMIN" ]
          env:
            - name: DELAY
              value: "20ms"
            - name: JITTER
              value: "6ms"
            - name: HTTP_PORT
              value: "8080"
            - name: RABBITMQ_EXCHANGE_KIND
              value: "topic"

          command: [ "sh","-c" ]
          args:
            - >
              apk add --no-cache iproute2 &&
              tc qdisc del dev eth0 root 2>/dev/null || true &&
              tc qdisc add dev eth0 root netem delay ${DELAY} ${JITTER} distribution normal &&
              tc qdisc show dev eth0

      nodeSelector:
        role: fog
      containers:
        - name: event-service
          image: sdcc/event-service:local
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: mqtt-common
            - secretRef:
                name: mqtt-credentials
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            # includo anche la variante minuscola per robustezza
            - name: EVENT_SUB_TOPICS
              value: "event/irrigationDecision/#,event/StateChange/#"
            - name: INFLUX_URL
              value: "http://influxdb-fog.fog.svc:8086"
            - name: INFLUX_ORG
              value: "msut"
            - name: INFLUX_BUCKET
              value: "events"
            - name: INFLUX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-fog-auth
                  key: INFLUXDB_TOKEN
            - name: WRITE_BATCH_SIZE
              value: "10"
            - name: WRITE_FLUSH_INTERVAL_MS
              value: "200"
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: event-service
  namespace: fog
spec:
  type: NodePort
  selector:
    app: event-service
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 30080   # porta esterna del nodo (persistente)
